spring:
  application:
    name: smart-startup-navigator
 # springAi
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
      read-timeout: 600
    mcp:
        client:
            stdio:
              servers-configuration: classpath:mcp-servers.json
  # application-local.yml
  profiles:
    active: local
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: ${DATASOURCE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource


server:
  port: 8456
  servlet:
    context-path: /api

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.gyqstd.smartstartupnavigator.controller, com.gyqstd.smartstartupnavigator.demo

# searchApi
search-api:
  api-key: ${SEARCH_API_KEY}